# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-19 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180119_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_college',
            field=models.ManyToManyField(to='employee.College'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_primary',
            field=models.ManyToManyField(to='employee.Primary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_secondary',
            field=models.ManyToManyField(to='employee.Secondary'),
        ),
        migrations.AlterField(
            model_name='address',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 694000)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 697000)),
        ),
        migrations.AlterField(
            model_name='civil_status',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 702000)),
        ),
        migrations.AlterField(
            model_name='college',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 695000)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 688000)),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 695000)),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 693000)),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 705000)),
        ),
        migrations.AlterField(
            model_name='primary',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='province',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 697000)),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 698000)),
        ),
        migrations.AlterField(
            model_name='religion',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 21, 34, 37, 696000)),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
