# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-29 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20180129_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.IntegerField(default=1)),
                ('date_entered', models.DateTimeField(null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'educ_college',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 327000)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 331000)),
        ),
        migrations.AlterField(
            model_name='civil_status',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 342000)),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 328000)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 321000)),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 329000)),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 326000)),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 349000)),
        ),
        migrations.AlterField(
            model_name='province',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 332000)),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 332000)),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 330000)),
        ),
        migrations.AlterField(
            model_name='religion',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 16, 55, 26, 330000)),
        ),
    ]
