# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-30 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20180130_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeposition',
            old_name='name',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='address',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 829000)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 833000)),
        ),
        migrations.AlterField(
            model_name='civil_status',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 840000)),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 830000)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 822000)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.ManyToManyField(to='employee.Positions'),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 831000)),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 828000)),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 843000)),
        ),
        migrations.AlterField(
            model_name='province',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 834000)),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 834000)),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 832000)),
        ),
        migrations.AlterField(
            model_name='religion',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 17, 46, 29, 832000)),
        ),
    ]
